language: python

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - linux-libc-dev
    - git
    - build-essential
    - automake
    - libtool
    - python-dev
    - zlib1g-dev
    - gettext
    - swig
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - libfreetype6-dev
    - libsigc++-2.0-dev
    - libfribidi-dev
    - libssl-dev
    - libavahi-client-dev
    - libjpeg-turbo8-dev
    - libgif-dev

python:
  - "2.7"

git:
  depth: 1

script:
- echo compiling persianempire enigma2 plugins
- autoreconf -i
- ./configure --with-libsdl=no --with-boxtype=nobox --enable-dependency-tracking ac_cv_prog_c_openmp=-fopenmp --with-gstversion=1.0 --with-textlcd
- make
- python -m compileall .
- echo done!
